### ISSUE TITLE
Выбор базы данных

### ISSUE THREAD

**Issue by geraldus** [geraldus/quyang-ui#1]
База данных может быть выбрана любая.  Есть два варианта: использовать NoSQL базы данных, например Mongo DB; или SQL базы данных, например PostgreSQL.

При использовании SQL базы данных возникнут трудности с получением метаданных.  К примеру, у нас есть 2 типа ИНН: физ.лица и юр.лица.  В SQL БД подобную схему можно реализовать слелующим образом:

```
Таблица ИНН
===========
- id
- номер ИНН

Таблица физ.лиц
==============
- id
- связанный ИНН (id)
- Фамилия
- Имя
- Отчество
... прочие данные 

Таблица юр.лиц
=============
- id 
- связанный ИНН (id)
- Полное наименование
- ОГРН
- КПП
- Юр.адрес
- Физ.адрес
- ... прочие данные
```

Такая схема делает удобным хранение, но получать связанные данные нужно будет с помощью присоединения (SELECT INNER JOIN), что усложняет жизнь программистов во многих случаях.  К тому же при изменении структуры метаданных или их расширении нередко будут возникать трудности с миграциями таблиц.

При NoSQL подходе, мы просто описываем объект, к примеру, Контрагент, а поля (метаданные) могут быть любыми, так же легко можно будет добавлять новые поля (параметры).  В этом случае обязательно иметь некую спецификацию того, какие поля должны быть у объектов (в прочем, она у нас и так есть).  NoSQL подход удобен своей гибкостью и принципом "вложенных документов".  Но при правильном использовании SQL БД будет работать быстрее, чем NoSQL.

Нужна ли помощь по БД?  Могу описать альтернативные способы описания таблиц в случае выбора SQL подхода.

**Comment by likeahuman** [comment]
вопросы:
1. В какой БД будет быстрее расти размер файла базы, при одинаковом объеме данных?
2. какова боль перехода с одной на другую, при достаточном объеме, через год, или два

**Comment by geraldus** [comment]
> 1. В какой БД будет быстрее расти размер файла базы, при одинаковом объеме данных?
Размеры и темпы роста сопоставимы. 

> 2. какова боль перехода с одной на другую, при достаточном объеме, через год, или два

Через год или два боли будет достаточно: не проблема перенести данные из одной базы в другую, проблема в переписывании всего функционала, связанного с обращением к базе дынных (чтение / запись).  То есть боль пропорциональна функциональности.

**Comment by likeahuman** [comment]
а сам что думаешь?

**Comment by geraldus** [comment]
> а сам что думаешь?

NoSQL кажется привлекательной, я уже видел масштабные проекты подобного рода на NoSQL.  Однако SQL подход хоть и кажется немного "деревянным", но одновременно и более "точным".

**Comment by geraldus** [comment]
Выбрали PostgreSQL
